// Code generated by protoc-gen-go. DO NOT EDIT.
// source: booking-service.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Ticket struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Cinema               string   `protobuf:"bytes,2,opt,name=cinema,proto3" json:"cinema,omitempty"`
	Movie                string   `protobuf:"bytes,3,opt,name=movie,proto3" json:"movie,omitempty"`
	OrderId              string   `protobuf:"bytes,4,opt,name=orderId,proto3" json:"orderId,omitempty"`
	TotalAmount          int64    `protobuf:"varint,5,opt,name=totalAmount,proto3" json:"totalAmount,omitempty"`
	User                 *User    `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ticket) Reset()         { *m = Ticket{} }
func (m *Ticket) String() string { return proto.CompactTextString(m) }
func (*Ticket) ProtoMessage()    {}
func (*Ticket) Descriptor() ([]byte, []int) {
	return fileDescriptor_add7f4b93d8645af, []int{0}
}

func (m *Ticket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ticket.Unmarshal(m, b)
}
func (m *Ticket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ticket.Marshal(b, m, deterministic)
}
func (m *Ticket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ticket.Merge(m, src)
}
func (m *Ticket) XXX_Size() int {
	return xxx_messageInfo_Ticket.Size(m)
}
func (m *Ticket) XXX_DiscardUnknown() {
	xxx_messageInfo_Ticket.DiscardUnknown(m)
}

var xxx_messageInfo_Ticket proto.InternalMessageInfo

func (m *Ticket) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *Ticket) GetCinema() string {
	if m != nil {
		return m.Cinema
	}
	return ""
}

func (m *Ticket) GetMovie() string {
	if m != nil {
		return m.Movie
	}
	return ""
}

func (m *Ticket) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *Ticket) GetTotalAmount() int64 {
	if m != nil {
		return m.TotalAmount
	}
	return 0
}

func (m *Ticket) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type User struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,4,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_add7f4b93d8645af, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type BookingRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	ShowingId            int64    `protobuf:"varint,2,opt,name=showingId,proto3" json:"showingId,omitempty"`
	TotalAmount          int64    `protobuf:"varint,3,opt,name=totalAmount,proto3" json:"totalAmount,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,4,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookingRequest) Reset()         { *m = BookingRequest{} }
func (m *BookingRequest) String() string { return proto.CompactTextString(m) }
func (*BookingRequest) ProtoMessage()    {}
func (*BookingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_add7f4b93d8645af, []int{2}
}

func (m *BookingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookingRequest.Unmarshal(m, b)
}
func (m *BookingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookingRequest.Marshal(b, m, deterministic)
}
func (m *BookingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookingRequest.Merge(m, src)
}
func (m *BookingRequest) XXX_Size() int {
	return xxx_messageInfo_BookingRequest.Size(m)
}
func (m *BookingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BookingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BookingRequest proto.InternalMessageInfo

func (m *BookingRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *BookingRequest) GetShowingId() int64 {
	if m != nil {
		return m.ShowingId
	}
	return 0
}

func (m *BookingRequest) GetTotalAmount() int64 {
	if m != nil {
		return m.TotalAmount
	}
	return 0
}

func (m *BookingRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func init() {
	proto.RegisterType((*Ticket)(nil), "v1.Ticket")
	proto.RegisterType((*User)(nil), "v1.User")
	proto.RegisterType((*BookingRequest)(nil), "v1.BookingRequest")
}

func init() { proto.RegisterFile("booking-service.proto", fileDescriptor_add7f4b93d8645af) }

var fileDescriptor_add7f4b93d8645af = []byte{
	// 498 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x41, 0x6f, 0xd3, 0x3e,
	0x18, 0xc6, 0xe5, 0xa6, 0xeb, 0x36, 0x57, 0xff, 0xff, 0x2a, 0x8b, 0x4d, 0x51, 0xd5, 0x83, 0x95,
	0x53, 0x55, 0xd1, 0x64, 0x2d, 0x3d, 0x95, 0x0b, 0xdb, 0x05, 0xed, 0xb2, 0x43, 0x00, 0x09, 0x8e,
	0x6e, 0xfa, 0x2a, 0x31, 0x6d, 0xfc, 0x06, 0xdb, 0x49, 0x39, 0x23, 0x3e, 0x01, 0xdc, 0x38, 0xf2,
	0x95, 0x90, 0x38, 0x70, 0xe6, 0x83, 0xa0, 0x38, 0xd9, 0x28, 0x2b, 0x12, 0xa7, 0xf8, 0xf9, 0xe5,
	0xb1, 0xfc, 0xf8, 0xf5, 0x43, 0xcf, 0x57, 0x88, 0x1b, 0xa9, 0xd2, 0xa9, 0x01, 0x5d, 0xc9, 0x04,
	0xc2, 0x42, 0xa3, 0x45, 0xd6, 0xa9, 0x66, 0xc3, 0x51, 0x8a, 0x98, 0x6e, 0x21, 0x12, 0x85, 0x8c,
	0x84, 0x52, 0x68, 0x85, 0x95, 0xa8, 0x4c, 0xe3, 0x18, 0x3e, 0x76, 0x9f, 0x64, 0x9a, 0x82, 0x9a,
	0x9a, 0x9d, 0x48, 0x53, 0xd0, 0x11, 0x16, 0xce, 0x71, 0xe8, 0x0e, 0xbe, 0x12, 0xda, 0x7b, 0x29,
	0x93, 0x0d, 0x58, 0x36, 0xa0, 0x9e, 0x28, 0xa4, 0x4f, 0x38, 0x19, 0x9f, 0xc6, 0xf5, 0x92, 0x5d,
	0xd0, 0x5e, 0x22, 0x15, 0xe4, 0xc2, 0xef, 0x38, 0xd8, 0x2a, 0xf6, 0x88, 0x1e, 0xe5, 0x58, 0x49,
	0xf0, 0x3d, 0x87, 0x1b, 0xc1, 0x7c, 0x7a, 0x8c, 0x7a, 0x0d, 0xfa, 0x66, 0xed, 0x77, 0x1d, 0xbf,
	0x93, 0x8c, 0xd3, 0xbe, 0x45, 0x2b, 0xb6, 0x57, 0x39, 0x96, 0xca, 0xfa, 0x47, 0x9c, 0x8c, 0xbd,
	0x78, 0x1f, 0xb1, 0x11, 0xed, 0x96, 0x06, 0xb4, 0xdf, 0xe3, 0x64, 0xdc, 0x9f, 0x9f, 0x84, 0xd5,
	0x2c, 0x7c, 0x65, 0x40, 0xc7, 0x8e, 0x06, 0x8a, 0x76, 0x6b, 0xc5, 0x18, 0xed, 0x2a, 0x91, 0x43,
	0x1b, 0xd1, 0xad, 0xd9, 0x90, 0x9e, 0x6c, 0x85, 0xb1, 0xb7, 0x35, 0x6f, 0x52, 0xde, 0xeb, 0x3a,
	0x27, 0xe4, 0x42, 0x6e, 0xef, 0x72, 0x3a, 0x51, 0xa7, 0x29, 0x32, 0x54, 0x70, 0x5b, 0xe6, 0x2b,
	0xd0, 0x6d, 0xd6, 0x7d, 0x14, 0x7c, 0x24, 0xf4, 0xff, 0xeb, 0x66, 0xfc, 0x31, 0xbc, 0x2b, 0xc1,
	0xfc, 0x6d, 0x38, 0x23, 0x7a, 0x6a, 0x32, 0xdc, 0x49, 0x95, 0xde, 0xac, 0xdd, 0xc9, 0x5e, 0xfc,
	0x1b, 0x3c, 0xbc, 0xb2, 0x77, 0x78, 0xe5, 0x7f, 0xc6, 0x98, 0xbf, 0xb9, 0x4f, 0xf1, 0xa2, 0xe9,
	0x00, 0x7b, 0x4e, 0xff, 0x4b, 0x34, 0x08, 0x0b, 0x2d, 0x67, 0xac, 0x9e, 0xd4, 0x9f, 0x51, 0x87,
	0xb4, 0x66, 0xcd, 0x9b, 0x06, 0x17, 0x1f, 0xbe, 0xfd, 0xfc, 0xdc, 0x19, 0x04, 0xfd, 0xa8, 0x9a,
	0x45, 0x6d, 0xa3, 0x96, 0x64, 0x72, 0xfd, 0x83, 0x7c, 0xba, 0xfa, 0x4e, 0x58, 0x41, 0xcf, 0xda,
	0xcd, 0xbc, 0xad, 0x59, 0xf0, 0x9a, 0x9e, 0x35, 0xaf, 0x3c, 0x6d, 0xed, 0x86, 0x85, 0x99, 0xb5,
	0x85, 0x59, 0x46, 0x51, 0x2a, 0x6d, 0x56, 0xae, 0xc2, 0x04, 0xf3, 0x28, 0x43, 0xa1, 0xd2, 0xd5,
	0xc6, 0x42, 0x92, 0x45, 0x0f, 0xfc, 0xc3, 0xf3, 0xbd, 0x9f, 0xcf, 0xd2, 0x7a, 0xe6, 0xf5, 0x96,
	0xb9, 0x37, 0x0b, 0x2f, 0x27, 0x84, 0xcc, 0x07, 0xa2, 0x28, 0xb6, 0x32, 0x71, 0x35, 0x8c, 0xde,
	0x1a, 0x54, 0xcb, 0x03, 0x12, 0x3f, 0xa5, 0xde, 0xe2, 0x72, 0xc1, 0x16, 0x74, 0x12, 0x83, 0x2d,
	0xb5, 0x82, 0x35, 0xdf, 0x65, 0xa0, 0xb8, 0xcd, 0x80, 0x6b, 0x30, 0x58, 0xea, 0x04, 0xf8, 0x1a,
	0xc1, 0x70, 0x85, 0x96, 0xc3, 0x7b, 0x69, 0x6c, 0xc8, 0x7a, 0xb4, 0xfb, 0xa5, 0x43, 0x8e, 0x57,
	0x3d, 0x57, 0xed, 0x27, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x96, 0xec, 0xf9, 0x27, 0x43, 0x03,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BookingServiceClient is the client API for BookingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BookingServiceClient interface {
	CreateBooking(ctx context.Context, in *BookingRequest, opts ...grpc.CallOption) (*Ticket, error)
}

type bookingServiceClient struct {
	cc *grpc.ClientConn
}

func NewBookingServiceClient(cc *grpc.ClientConn) BookingServiceClient {
	return &bookingServiceClient{cc}
}

func (c *bookingServiceClient) CreateBooking(ctx context.Context, in *BookingRequest, opts ...grpc.CallOption) (*Ticket, error) {
	out := new(Ticket)
	err := c.cc.Invoke(ctx, "/v1.BookingService/createBooking", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookingServiceServer is the server API for BookingService service.
type BookingServiceServer interface {
	CreateBooking(context.Context, *BookingRequest) (*Ticket, error)
}

func RegisterBookingServiceServer(s *grpc.Server, srv BookingServiceServer) {
	s.RegisterService(&_BookingService_serviceDesc, srv)
}

func _BookingService_CreateBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServiceServer).CreateBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.BookingService/CreateBooking",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServiceServer).CreateBooking(ctx, req.(*BookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BookingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.BookingService",
	HandlerType: (*BookingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "createBooking",
			Handler:    _BookingService_CreateBooking_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "booking-service.proto",
}
