// Code generated by protoc-gen-go. DO NOT EDIT.
// source: document-service.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Ticket struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Cinema               string   `protobuf:"bytes,2,opt,name=cinema,proto3" json:"cinema,omitempty"`
	Movie                string   `protobuf:"bytes,3,opt,name=movie,proto3" json:"movie,omitempty"`
	OrderId              string   `protobuf:"bytes,4,opt,name=orderId,proto3" json:"orderId,omitempty"`
	TotalAmount          int64    `protobuf:"varint,5,opt,name=totalAmount,proto3" json:"totalAmount,omitempty"`
	User                 *User    `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ticket) Reset()         { *m = Ticket{} }
func (m *Ticket) String() string { return proto.CompactTextString(m) }
func (*Ticket) ProtoMessage()    {}
func (*Ticket) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a1c7d71a4d4c3a0, []int{0}
}

func (m *Ticket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ticket.Unmarshal(m, b)
}
func (m *Ticket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ticket.Marshal(b, m, deterministic)
}
func (m *Ticket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ticket.Merge(m, src)
}
func (m *Ticket) XXX_Size() int {
	return xxx_messageInfo_Ticket.Size(m)
}
func (m *Ticket) XXX_DiscardUnknown() {
	xxx_messageInfo_Ticket.DiscardUnknown(m)
}

var xxx_messageInfo_Ticket proto.InternalMessageInfo

func (m *Ticket) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *Ticket) GetCinema() string {
	if m != nil {
		return m.Cinema
	}
	return ""
}

func (m *Ticket) GetMovie() string {
	if m != nil {
		return m.Movie
	}
	return ""
}

func (m *Ticket) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *Ticket) GetTotalAmount() int64 {
	if m != nil {
		return m.TotalAmount
	}
	return 0
}

func (m *Ticket) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type User struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,4,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a1c7d71a4d4c3a0, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type HTMLResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Html                 string   `protobuf:"bytes,2,opt,name=html,proto3" json:"html,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HTMLResponse) Reset()         { *m = HTMLResponse{} }
func (m *HTMLResponse) String() string { return proto.CompactTextString(m) }
func (*HTMLResponse) ProtoMessage()    {}
func (*HTMLResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a1c7d71a4d4c3a0, []int{2}
}

func (m *HTMLResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HTMLResponse.Unmarshal(m, b)
}
func (m *HTMLResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HTMLResponse.Marshal(b, m, deterministic)
}
func (m *HTMLResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HTMLResponse.Merge(m, src)
}
func (m *HTMLResponse) XXX_Size() int {
	return xxx_messageInfo_HTMLResponse.Size(m)
}
func (m *HTMLResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HTMLResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HTMLResponse proto.InternalMessageInfo

func (m *HTMLResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *HTMLResponse) GetHtml() string {
	if m != nil {
		return m.Html
	}
	return ""
}

type AlertTemplateRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Cinema               string   `protobuf:"bytes,2,opt,name=cinema,proto3" json:"cinema,omitempty"`
	Movie                string   `protobuf:"bytes,3,opt,name=movie,proto3" json:"movie,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AlertTemplateRequest) Reset()         { *m = AlertTemplateRequest{} }
func (m *AlertTemplateRequest) String() string { return proto.CompactTextString(m) }
func (*AlertTemplateRequest) ProtoMessage()    {}
func (*AlertTemplateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a1c7d71a4d4c3a0, []int{3}
}

func (m *AlertTemplateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlertTemplateRequest.Unmarshal(m, b)
}
func (m *AlertTemplateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlertTemplateRequest.Marshal(b, m, deterministic)
}
func (m *AlertTemplateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlertTemplateRequest.Merge(m, src)
}
func (m *AlertTemplateRequest) XXX_Size() int {
	return xxx_messageInfo_AlertTemplateRequest.Size(m)
}
func (m *AlertTemplateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AlertTemplateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AlertTemplateRequest proto.InternalMessageInfo

func (m *AlertTemplateRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *AlertTemplateRequest) GetCinema() string {
	if m != nil {
		return m.Cinema
	}
	return ""
}

func (m *AlertTemplateRequest) GetMovie() string {
	if m != nil {
		return m.Movie
	}
	return ""
}

func init() {
	proto.RegisterType((*Ticket)(nil), "v1.Ticket")
	proto.RegisterType((*User)(nil), "v1.User")
	proto.RegisterType((*HTMLResponse)(nil), "v1.HTMLResponse")
	proto.RegisterType((*AlertTemplateRequest)(nil), "v1.AlertTemplateRequest")
}

func init() { proto.RegisterFile("document-service.proto", fileDescriptor_6a1c7d71a4d4c3a0) }

var fileDescriptor_6a1c7d71a4d4c3a0 = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xc1, 0x6e, 0xe2, 0x30,
	0x10, 0x86, 0x15, 0x08, 0x59, 0x76, 0x58, 0x69, 0x91, 0x85, 0x90, 0x17, 0x71, 0x88, 0x72, 0xe2,
	0xb2, 0x20, 0x68, 0x2f, 0x3d, 0x22, 0xb5, 0x55, 0x2b, 0xb5, 0x1c, 0x52, 0xda, 0xbb, 0x09, 0x23,
	0xb0, 0x1a, 0xdb, 0xa9, 0xed, 0xe4, 0x49, 0xfa, 0x04, 0x7d, 0xd2, 0xca, 0x4e, 0xa8, 0x40, 0xe5,
	0xd6, 0xdb, 0xff, 0xff, 0xb1, 0x33, 0xdf, 0xcc, 0x18, 0x86, 0x5b, 0x95, 0x95, 0x02, 0xa5, 0xfd,
	0x6f, 0x50, 0x57, 0x3c, 0xc3, 0x69, 0xa1, 0x95, 0x55, 0xa4, 0x55, 0xcd, 0x47, 0xe3, 0x9d, 0x52,
	0xbb, 0x1c, 0x67, 0xac, 0xe0, 0x33, 0x26, 0xa5, 0xb2, 0xcc, 0x72, 0x25, 0x4d, 0x7d, 0x22, 0xf9,
	0x08, 0x20, 0x5a, 0xf3, 0xec, 0x15, 0x2d, 0xe9, 0x43, 0x9b, 0x15, 0x9c, 0x06, 0x71, 0x30, 0xf9,
	0x9d, 0x3a, 0x49, 0x86, 0x10, 0x65, 0x5c, 0xa2, 0x60, 0xb4, 0xe5, 0xc3, 0xc6, 0x91, 0x01, 0x74,
	0x84, 0xaa, 0x38, 0xd2, 0xb6, 0x8f, 0x6b, 0x43, 0x28, 0xfc, 0x52, 0x7a, 0x8b, 0xfa, 0x7e, 0x4b,
	0x43, 0x9f, 0x1f, 0x2c, 0x89, 0xa1, 0x67, 0x95, 0x65, 0xf9, 0x52, 0xa8, 0x52, 0x5a, 0xda, 0x89,
	0x83, 0x49, 0x3b, 0x3d, 0x8e, 0xc8, 0x18, 0xc2, 0xd2, 0xa0, 0xa6, 0x51, 0x1c, 0x4c, 0x7a, 0x8b,
	0xee, 0xb4, 0x9a, 0x4f, 0x9f, 0x0d, 0xea, 0xd4, 0xa7, 0x89, 0x84, 0xd0, 0x39, 0x42, 0x20, 0x94,
	0x4c, 0x60, 0x83, 0xe8, 0x35, 0x19, 0x41, 0x37, 0x67, 0xc6, 0xae, 0x5c, 0x5e, 0x53, 0x7e, 0x79,
	0xc7, 0x89, 0x82, 0xf1, 0xfc, 0xc0, 0xe9, 0x8d, 0xa3, 0x29, 0xf6, 0x4a, 0xe2, 0xaa, 0x14, 0x1b,
	0xd4, 0x0d, 0xeb, 0x71, 0x94, 0x5c, 0xc2, 0x9f, 0xbb, 0xf5, 0xe3, 0x43, 0x8a, 0xa6, 0x50, 0xd2,
	0xe0, 0x99, 0xc9, 0x10, 0x08, 0xf7, 0x56, 0xe4, 0x4d, 0x45, 0xaf, 0x93, 0x17, 0x18, 0x2c, 0x73,
	0xd4, 0x76, 0x8d, 0xa2, 0xc8, 0x99, 0xc5, 0x14, 0xdf, 0x4a, 0x34, 0x3f, 0x9e, 0xeb, 0xe2, 0x3d,
	0x80, 0xbf, 0xd7, 0xcd, 0x7e, 0x9f, 0xea, 0xf5, 0x92, 0x2b, 0xf8, 0x97, 0x69, 0x64, 0x16, 0xeb,
	0xdd, 0xdd, 0xb8, 0xc6, 0x0e, 0x75, 0x09, 0xb8, 0xf1, 0xd5, 0x1f, 0x46, 0x7d, 0xa7, 0x4f, 0x9a,
	0xb9, 0x05, 0x5a, 0x5f, 0xf5, 0xb0, 0xa7, 0x37, 0xa9, 0x3b, 0x7d, 0xae, 0x89, 0xef, 0xff, 0xd9,
	0x44, 0xfe, 0x01, 0x5d, 0x7c, 0x06, 0x00, 0x00, 0xff, 0xff, 0xa2, 0xc5, 0xfc, 0x57, 0x7c, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DocumentServiceClient is the client API for DocumentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DocumentServiceClient interface {
	CreateTicketEmailTemplate(ctx context.Context, in *Ticket, opts ...grpc.CallOption) (*HTMLResponse, error)
	CreateAlertEmailTemplate(ctx context.Context, in *AlertTemplateRequest, opts ...grpc.CallOption) (*HTMLResponse, error)
}

type documentServiceClient struct {
	cc *grpc.ClientConn
}

func NewDocumentServiceClient(cc *grpc.ClientConn) DocumentServiceClient {
	return &documentServiceClient{cc}
}

func (c *documentServiceClient) CreateTicketEmailTemplate(ctx context.Context, in *Ticket, opts ...grpc.CallOption) (*HTMLResponse, error) {
	out := new(HTMLResponse)
	err := c.cc.Invoke(ctx, "/v1.DocumentService/createTicketEmailTemplate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) CreateAlertEmailTemplate(ctx context.Context, in *AlertTemplateRequest, opts ...grpc.CallOption) (*HTMLResponse, error) {
	out := new(HTMLResponse)
	err := c.cc.Invoke(ctx, "/v1.DocumentService/createAlertEmailTemplate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentServiceServer is the server API for DocumentService service.
type DocumentServiceServer interface {
	CreateTicketEmailTemplate(context.Context, *Ticket) (*HTMLResponse, error)
	CreateAlertEmailTemplate(context.Context, *AlertTemplateRequest) (*HTMLResponse, error)
}

func RegisterDocumentServiceServer(s *grpc.Server, srv DocumentServiceServer) {
	s.RegisterService(&_DocumentService_serviceDesc, srv)
}

func _DocumentService_CreateTicketEmailTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ticket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).CreateTicketEmailTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.DocumentService/CreateTicketEmailTemplate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).CreateTicketEmailTemplate(ctx, req.(*Ticket))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_CreateAlertEmailTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlertTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).CreateAlertEmailTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.DocumentService/CreateAlertEmailTemplate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).CreateAlertEmailTemplate(ctx, req.(*AlertTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DocumentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.DocumentService",
	HandlerType: (*DocumentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "createTicketEmailTemplate",
			Handler:    _DocumentService_CreateTicketEmailTemplate_Handler,
		},
		{
			MethodName: "createAlertEmailTemplate",
			Handler:    _DocumentService_CreateAlertEmailTemplate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "document-service.proto",
}
