// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cinema-service.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Cinema struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Capacity             int64    `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cinema) Reset()         { *m = Cinema{} }
func (m *Cinema) String() string { return proto.CompactTextString(m) }
func (*Cinema) ProtoMessage()    {}
func (*Cinema) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb30e44d44370721, []int{0}
}

func (m *Cinema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cinema.Unmarshal(m, b)
}
func (m *Cinema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cinema.Marshal(b, m, deterministic)
}
func (m *Cinema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cinema.Merge(m, src)
}
func (m *Cinema) XXX_Size() int {
	return xxx_messageInfo_Cinema.Size(m)
}
func (m *Cinema) XXX_DiscardUnknown() {
	xxx_messageInfo_Cinema.DiscardUnknown(m)
}

var xxx_messageInfo_Cinema proto.InternalMessageInfo

func (m *Cinema) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Cinema) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Cinema) GetCapacity() int64 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

type Showing struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MovieId              int64    `protobuf:"varint,2,opt,name=movieId,proto3" json:"movieId,omitempty"`
	Time                 string   `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	IsNotify             int64    `protobuf:"varint,4,opt,name=isNotify,proto3" json:"isNotify,omitempty"`
	TicketAmounts        int64    `protobuf:"varint,5,opt,name=ticketAmounts,proto3" json:"ticketAmounts,omitempty"`
	Cinema               *Cinema  `protobuf:"bytes,6,opt,name=cinema,proto3" json:"cinema,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Showing) Reset()         { *m = Showing{} }
func (m *Showing) String() string { return proto.CompactTextString(m) }
func (*Showing) ProtoMessage()    {}
func (*Showing) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb30e44d44370721, []int{1}
}

func (m *Showing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Showing.Unmarshal(m, b)
}
func (m *Showing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Showing.Marshal(b, m, deterministic)
}
func (m *Showing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Showing.Merge(m, src)
}
func (m *Showing) XXX_Size() int {
	return xxx_messageInfo_Showing.Size(m)
}
func (m *Showing) XXX_DiscardUnknown() {
	xxx_messageInfo_Showing.DiscardUnknown(m)
}

var xxx_messageInfo_Showing proto.InternalMessageInfo

func (m *Showing) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Showing) GetMovieId() int64 {
	if m != nil {
		return m.MovieId
	}
	return 0
}

func (m *Showing) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *Showing) GetIsNotify() int64 {
	if m != nil {
		return m.IsNotify
	}
	return 0
}

func (m *Showing) GetTicketAmounts() int64 {
	if m != nil {
		return m.TicketAmounts
	}
	return 0
}

func (m *Showing) GetCinema() *Cinema {
	if m != nil {
		return m.Cinema
	}
	return nil
}

type ReadCinemaRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadCinemaRequest) Reset()         { *m = ReadCinemaRequest{} }
func (m *ReadCinemaRequest) String() string { return proto.CompactTextString(m) }
func (*ReadCinemaRequest) ProtoMessage()    {}
func (*ReadCinemaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb30e44d44370721, []int{2}
}

func (m *ReadCinemaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadCinemaRequest.Unmarshal(m, b)
}
func (m *ReadCinemaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadCinemaRequest.Marshal(b, m, deterministic)
}
func (m *ReadCinemaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadCinemaRequest.Merge(m, src)
}
func (m *ReadCinemaRequest) XXX_Size() int {
	return xxx_messageInfo_ReadCinemaRequest.Size(m)
}
func (m *ReadCinemaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadCinemaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadCinemaRequest proto.InternalMessageInfo

func (m *ReadCinemaRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ReadCinemaRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ReadCinemaResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Cinema               *Cinema  `protobuf:"bytes,2,opt,name=cinema,proto3" json:"cinema,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadCinemaResponse) Reset()         { *m = ReadCinemaResponse{} }
func (m *ReadCinemaResponse) String() string { return proto.CompactTextString(m) }
func (*ReadCinemaResponse) ProtoMessage()    {}
func (*ReadCinemaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb30e44d44370721, []int{3}
}

func (m *ReadCinemaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadCinemaResponse.Unmarshal(m, b)
}
func (m *ReadCinemaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadCinemaResponse.Marshal(b, m, deterministic)
}
func (m *ReadCinemaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadCinemaResponse.Merge(m, src)
}
func (m *ReadCinemaResponse) XXX_Size() int {
	return xxx_messageInfo_ReadCinemaResponse.Size(m)
}
func (m *ReadCinemaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadCinemaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadCinemaResponse proto.InternalMessageInfo

func (m *ReadCinemaResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ReadCinemaResponse) GetCinema() *Cinema {
	if m != nil {
		return m.Cinema
	}
	return nil
}

type ReadShowingRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadShowingRequest) Reset()         { *m = ReadShowingRequest{} }
func (m *ReadShowingRequest) String() string { return proto.CompactTextString(m) }
func (*ReadShowingRequest) ProtoMessage()    {}
func (*ReadShowingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb30e44d44370721, []int{4}
}

func (m *ReadShowingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadShowingRequest.Unmarshal(m, b)
}
func (m *ReadShowingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadShowingRequest.Marshal(b, m, deterministic)
}
func (m *ReadShowingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadShowingRequest.Merge(m, src)
}
func (m *ReadShowingRequest) XXX_Size() int {
	return xxx_messageInfo_ReadShowingRequest.Size(m)
}
func (m *ReadShowingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadShowingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadShowingRequest proto.InternalMessageInfo

func (m *ReadShowingRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ReadShowingRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ReadShowingResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Showing              *Showing `protobuf:"bytes,2,opt,name=showing,proto3" json:"showing,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadShowingResponse) Reset()         { *m = ReadShowingResponse{} }
func (m *ReadShowingResponse) String() string { return proto.CompactTextString(m) }
func (*ReadShowingResponse) ProtoMessage()    {}
func (*ReadShowingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb30e44d44370721, []int{5}
}

func (m *ReadShowingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadShowingResponse.Unmarshal(m, b)
}
func (m *ReadShowingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadShowingResponse.Marshal(b, m, deterministic)
}
func (m *ReadShowingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadShowingResponse.Merge(m, src)
}
func (m *ReadShowingResponse) XXX_Size() int {
	return xxx_messageInfo_ReadShowingResponse.Size(m)
}
func (m *ReadShowingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadShowingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadShowingResponse proto.InternalMessageInfo

func (m *ReadShowingResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ReadShowingResponse) GetShowing() *Showing {
	if m != nil {
		return m.Showing
	}
	return nil
}

type SetNotifyRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	ShowingId            int64    `protobuf:"varint,2,opt,name=showingId,proto3" json:"showingId,omitempty"`
	Value                int64    `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetNotifyRequest) Reset()         { *m = SetNotifyRequest{} }
func (m *SetNotifyRequest) String() string { return proto.CompactTextString(m) }
func (*SetNotifyRequest) ProtoMessage()    {}
func (*SetNotifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb30e44d44370721, []int{6}
}

func (m *SetNotifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetNotifyRequest.Unmarshal(m, b)
}
func (m *SetNotifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetNotifyRequest.Marshal(b, m, deterministic)
}
func (m *SetNotifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetNotifyRequest.Merge(m, src)
}
func (m *SetNotifyRequest) XXX_Size() int {
	return xxx_messageInfo_SetNotifyRequest.Size(m)
}
func (m *SetNotifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetNotifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetNotifyRequest proto.InternalMessageInfo

func (m *SetNotifyRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *SetNotifyRequest) GetShowingId() int64 {
	if m != nil {
		return m.ShowingId
	}
	return 0
}

func (m *SetNotifyRequest) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type SetNotifyResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Result               int64    `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetNotifyResponse) Reset()         { *m = SetNotifyResponse{} }
func (m *SetNotifyResponse) String() string { return proto.CompactTextString(m) }
func (*SetNotifyResponse) ProtoMessage()    {}
func (*SetNotifyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb30e44d44370721, []int{7}
}

func (m *SetNotifyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetNotifyResponse.Unmarshal(m, b)
}
func (m *SetNotifyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetNotifyResponse.Marshal(b, m, deterministic)
}
func (m *SetNotifyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetNotifyResponse.Merge(m, src)
}
func (m *SetNotifyResponse) XXX_Size() int {
	return xxx_messageInfo_SetNotifyResponse.Size(m)
}
func (m *SetNotifyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetNotifyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetNotifyResponse proto.InternalMessageInfo

func (m *SetNotifyResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *SetNotifyResponse) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*Cinema)(nil), "v1.Cinema")
	proto.RegisterType((*Showing)(nil), "v1.Showing")
	proto.RegisterType((*ReadCinemaRequest)(nil), "v1.ReadCinemaRequest")
	proto.RegisterType((*ReadCinemaResponse)(nil), "v1.ReadCinemaResponse")
	proto.RegisterType((*ReadShowingRequest)(nil), "v1.ReadShowingRequest")
	proto.RegisterType((*ReadShowingResponse)(nil), "v1.ReadShowingResponse")
	proto.RegisterType((*SetNotifyRequest)(nil), "v1.SetNotifyRequest")
	proto.RegisterType((*SetNotifyResponse)(nil), "v1.SetNotifyResponse")
}

func init() { proto.RegisterFile("cinema-service.proto", fileDescriptor_fb30e44d44370721) }

var fileDescriptor_fb30e44d44370721 = []byte{
	// 424 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4d, 0x8f, 0xda, 0x30,
	0x10, 0x55, 0x12, 0x08, 0xcd, 0x20, 0x2a, 0x70, 0x81, 0x46, 0x11, 0x07, 0x14, 0xb5, 0x12, 0x97,
	0x82, 0xa0, 0x6a, 0x55, 0xa9, 0x6a, 0xa5, 0xaa, 0x97, 0xb6, 0x07, 0x0e, 0xe1, 0xd2, 0xab, 0x9b,
	0xb8, 0xac, 0xb5, 0xc4, 0xce, 0x62, 0x27, 0x2b, 0x7e, 0xd4, 0xfe, 0x8d, 0xfd, 0x5d, 0xab, 0xd8,
	0x4e, 0xf8, 0xda, 0x48, 0x7b, 0xf3, 0xbc, 0xcc, 0x7b, 0xf3, 0xe6, 0xd9, 0x81, 0x61, 0x4c, 0x19,
	0x49, 0xf1, 0x07, 0x41, 0xf6, 0x05, 0x8d, 0xc9, 0x3c, 0xdb, 0x73, 0xc9, 0x91, 0x5d, 0x2c, 0x83,
	0xc9, 0x96, 0xf3, 0xed, 0x8e, 0x2c, 0x70, 0x46, 0x17, 0x98, 0x31, 0x2e, 0xb1, 0xa4, 0x9c, 0x09,
	0xdd, 0x11, 0xfe, 0x02, 0xf7, 0xa7, 0x62, 0xa2, 0xd7, 0x60, 0xd3, 0xc4, 0xb7, 0xa6, 0xd6, 0xcc,
	0x89, 0x6c, 0x9a, 0x20, 0x04, 0x2d, 0x86, 0x53, 0xe2, 0xdb, 0x53, 0x6b, 0xe6, 0x45, 0xea, 0x8c,
	0x02, 0x78, 0x15, 0xe3, 0x0c, 0xc7, 0x54, 0x1e, 0x7c, 0x47, 0x75, 0xd6, 0x75, 0xf8, 0x60, 0x41,
	0x67, 0x73, 0xc3, 0xef, 0x29, 0xdb, 0x5e, 0x69, 0xf9, 0xd0, 0x49, 0x79, 0x41, 0xc9, 0xef, 0x44,
	0xc9, 0x39, 0x51, 0x55, 0x96, 0x53, 0x24, 0x4d, 0x89, 0x52, 0xf3, 0x22, 0x75, 0x2e, 0xa7, 0x50,
	0xb1, 0xe6, 0x92, 0xfe, 0x3f, 0xf8, 0x2d, 0x3d, 0xa5, 0xaa, 0xd1, 0x3b, 0xe8, 0x49, 0x1a, 0xdf,
	0x12, 0xf9, 0x23, 0xe5, 0x39, 0x93, 0xc2, 0x6f, 0xab, 0x86, 0x73, 0x10, 0x85, 0xe0, 0xea, 0x3c,
	0x7c, 0x77, 0x6a, 0xcd, 0xba, 0x2b, 0x98, 0x17, 0xcb, 0xb9, 0xde, 0x33, 0x32, 0x5f, 0xc2, 0x4f,
	0x30, 0x88, 0x08, 0x4e, 0x0c, 0x4a, 0xee, 0x72, 0x22, 0x24, 0xea, 0x83, 0x83, 0x33, 0xaa, 0x9c,
	0x7b, 0x51, 0x79, 0x34, 0xab, 0xd8, 0xd5, 0x2a, 0xe1, 0x1f, 0x40, 0xa7, 0x34, 0x91, 0x71, 0x26,
	0xc8, 0x33, 0xbc, 0xa3, 0x05, 0xbb, 0xd1, 0xc2, 0x67, 0xad, 0x65, 0x52, 0x7b, 0xb9, 0x87, 0x35,
	0xbc, 0x39, 0xe3, 0x35, 0x9a, 0x78, 0x0f, 0x1d, 0xa1, 0x9b, 0x8c, 0x8b, 0x6e, 0xe9, 0xa2, 0xe2,
	0x55, 0xdf, 0xc2, 0xbf, 0xd0, 0xdf, 0x10, 0xa9, 0x13, 0x6e, 0x76, 0x31, 0x01, 0xcf, 0x10, 0xea,
	0x6b, 0x3c, 0x02, 0x68, 0x08, 0xed, 0x02, 0xef, 0x72, 0x62, 0xde, 0x85, 0x2e, 0xc2, 0x6f, 0x30,
	0x38, 0x51, 0x6e, 0xf4, 0x39, 0x06, 0x77, 0x4f, 0x44, 0xbe, 0x93, 0x46, 0xd7, 0x54, 0xab, 0x47,
	0x0b, 0x7a, 0x3a, 0xb3, 0x8d, 0x7e, 0xd7, 0xe8, 0x2b, 0xc0, 0x31, 0x7e, 0x34, 0x2a, 0xd7, 0xb9,
	0xba, 0xc5, 0x60, 0x7c, 0x09, 0x9b, 0xc1, 0xdf, 0xa1, 0x7b, 0x92, 0x1b, 0xaa, 0xdb, 0xce, 0x2f,
	0x20, 0x78, 0x7b, 0x85, 0x1b, 0xfe, 0x17, 0xf0, 0xea, 0x6d, 0xd0, 0x50, 0x45, 0x79, 0x11, 0x5b,
	0x30, 0xba, 0x40, 0x35, 0xf3, 0x9f, 0xab, 0xfe, 0xb6, 0x8f, 0x4f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x18, 0x0f, 0x89, 0xac, 0xa7, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CinemaServiceClient is the client API for CinemaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CinemaServiceClient interface {
	ReadCinema(ctx context.Context, in *ReadCinemaRequest, opts ...grpc.CallOption) (*ReadCinemaResponse, error)
	ReadShowing(ctx context.Context, in *ReadShowingRequest, opts ...grpc.CallOption) (*ReadShowingResponse, error)
	SetNotify(ctx context.Context, in *SetNotifyRequest, opts ...grpc.CallOption) (*SetNotifyResponse, error)
}

type cinemaServiceClient struct {
	cc *grpc.ClientConn
}

func NewCinemaServiceClient(cc *grpc.ClientConn) CinemaServiceClient {
	return &cinemaServiceClient{cc}
}

func (c *cinemaServiceClient) ReadCinema(ctx context.Context, in *ReadCinemaRequest, opts ...grpc.CallOption) (*ReadCinemaResponse, error) {
	out := new(ReadCinemaResponse)
	err := c.cc.Invoke(ctx, "/v1.CinemaService/ReadCinema", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cinemaServiceClient) ReadShowing(ctx context.Context, in *ReadShowingRequest, opts ...grpc.CallOption) (*ReadShowingResponse, error) {
	out := new(ReadShowingResponse)
	err := c.cc.Invoke(ctx, "/v1.CinemaService/ReadShowing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cinemaServiceClient) SetNotify(ctx context.Context, in *SetNotifyRequest, opts ...grpc.CallOption) (*SetNotifyResponse, error) {
	out := new(SetNotifyResponse)
	err := c.cc.Invoke(ctx, "/v1.CinemaService/SetNotify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CinemaServiceServer is the server API for CinemaService service.
type CinemaServiceServer interface {
	ReadCinema(context.Context, *ReadCinemaRequest) (*ReadCinemaResponse, error)
	ReadShowing(context.Context, *ReadShowingRequest) (*ReadShowingResponse, error)
	SetNotify(context.Context, *SetNotifyRequest) (*SetNotifyResponse, error)
}

func RegisterCinemaServiceServer(s *grpc.Server, srv CinemaServiceServer) {
	s.RegisterService(&_CinemaService_serviceDesc, srv)
}

func _CinemaService_ReadCinema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadCinemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CinemaServiceServer).ReadCinema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.CinemaService/ReadCinema",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CinemaServiceServer).ReadCinema(ctx, req.(*ReadCinemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CinemaService_ReadShowing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadShowingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CinemaServiceServer).ReadShowing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.CinemaService/ReadShowing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CinemaServiceServer).ReadShowing(ctx, req.(*ReadShowingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CinemaService_SetNotify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetNotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CinemaServiceServer).SetNotify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.CinemaService/SetNotify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CinemaServiceServer).SetNotify(ctx, req.(*SetNotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CinemaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.CinemaService",
	HandlerType: (*CinemaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadCinema",
			Handler:    _CinemaService_ReadCinema_Handler,
		},
		{
			MethodName: "ReadShowing",
			Handler:    _CinemaService_ReadShowing_Handler,
		},
		{
			MethodName: "SetNotify",
			Handler:    _CinemaService_SetNotify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cinema-service.proto",
}
